-- CreateEnum
CREATE TYPE "interviewstatus" AS ENUM ('PENDING_SETUP', 'PENDING_QUESTIONS', 'QUESTIONS_GENERATED', 'INTERVIEW_COMPLETED', 'INTERVIEW_CANCELLED');

-- AlterTable
ALTER TABLE "interviewcard" ADD COLUMN     "status" "interviewstatus" NOT NULL DEFAULT 'PENDING_QUESTIONS';
